export enum ColumnSize {
  ThreeQuarters = 'is-three-quarters',
  TwoThirds = 'is-two-thirds',
  Half = 'is-half',
  OneThird = 'is-one-third',
  OneQuarter = 'is-one-quarter',
  Full = 'is-full',
  FourFifths = 'is-four-fifths',
  ThreeFifths = 'is-three-fifths',
  TwoFifths = 'is-two-fifths',
  OneFifths = 'is-one-fifth',

  // 12 columns system
  One = 'is-1',
  Two = 'is-2',
  Three = 'is-3',
  Four = 'is-4',
  Five = 'is-5',
  Six = 'is-6',
  Seven = 'is-7',
  Eight = 'is-8',
  Nine = 'is-9',
  Ten = 'is-10',
  Eleven = 'is-11',
  Twelve = 'is-12',
}