export enum ColumnSize {
  ThreeQuarters = 'is-three-quarters',
  TwoThirds = 'is-two-thirds',
  Half = 'is-half',
  OneThird = 'is-one-third',
  OneQuarter = 'is-one-quarter',
  Full = 'is-full',
  FourFifths = 'is-four-fifths',
  ThreeFifths = 'is-three-fifths',
  TwoFifths = 'is-two-fifths',
  OneFifths = 'is-one-fifth',

  ThreeQuartersMobile = 'is-three-quarters-mobile',
  TwoThirdsMobile = 'is-two-thirds-mobile',
  HalfMobile = 'is-half-mobile',
  OneThirdMobile = 'is-one-third-mobile',
  OneQuarterMobile = 'is-one-quarter-mobile',
  FullMobile = 'is-full-mobile',
  FourFifthsMobile = 'is-four-fifths-mobile',
  ThreeFifthsMobile = 'is-three-fifths-mobile',
  TwoFifthsMobile = 'is-two-fifths-mobile',
  OneFifthsMobile = 'is-one-fifth-mobile',

  ThreeQuartersTablet = 'is-three-quarters-tablet',
  TwoThirdsTablet = 'is-two-thirds-tablet',
  HalfTablet = 'is-half-tablet',
  OneThirdTablet = 'is-one-third-tablet',
  OneQuarterTablet = 'is-one-quarter-tablet',
  FullTablet = 'is-full-tablet',
  FourFifthsTablet = 'is-four-fifths-tablet',
  ThreeFifthsTablet = 'is-three-fifths-tablet',
  TwoFifthsTablet = 'is-two-fifths-tablet',
  OneFifthsTablet = 'is-one-fifth-tablet',

  ThreeQuartersDesktop = 'is-three-quarters-desktop',
  TwoThirdsDesktop = 'is-two-thirds-desktop',
  HalfDesktop = 'is-half-desktop',
  OneThirdDesktop = 'is-one-third-desktop',
  OneQuarterDesktop = 'is-one-quarter-desktop',
  FullDesktop = 'is-full-desktop',
  FourFifthsDesktop = 'is-four-fifths-desktop',
  ThreeFifthsDesktop = 'is-three-fifths-desktop',
  TwoFifthsDesktop = 'is-two-fifths-desktop',
  OneFifthsDesktop = 'is-one-fifth-desktop',

  ThreeQuartersWidescreen = 'is-three-quarters-widescreen',
  TwoThirdsWidescreen = 'is-two-thirds-widescreen',
  HalfWidescreen = 'is-half-widescreen',
  OneThirdWidescreen = 'is-one-third-widescreen',
  OneQuarterWidescreen = 'is-one-quarter-widescreen',
  FullWidescreen = 'is-full-widescreen',
  FourFifthsWidescreen = 'is-four-fifths-widescreen',
  ThreeFifthsWidescreen = 'is-three-fifths-widescreen',
  TwoFifthsWidescreen = 'is-two-fifths-widescreen',
  OneFifthsWidescreen = 'is-one-fifth-widescreen',

  ThreeQuartersFullHD = 'is-three-quarters-fullhd',
  TwoThirdsFullHD = 'is-two-thirds-fullhd',
  HalfFullHD = 'is-half-fullhd',
  OneThirdFullHD = 'is-one-third-fullhd',
  OneQuarterFullHD = 'is-one-quarter-fullhd',
  FullFullHD = 'is-full-fullhd',
  FourFifthsFullHD = 'is-four-fifths-fullhd',
  ThreeFifthsFullHD = 'is-three-fifths-fullhd',
  TwoFifthsFullHD = 'is-two-fifths-fullhd',
  OneFifthsFullHD = 'is-one-fifth-fullhd',

  // 12 columns system
  One = 'is-1',
  Two = 'is-2',
  Three = 'is-3',
  Four = 'is-4',
  Five = 'is-5',
  Six = 'is-6',
  Seven = 'is-7',
  Eight = 'is-8',
  Nine = 'is-9',
  Ten = 'is-10',
  Eleven = 'is-11',
  Twelve = 'is-12',

  OneMobile = 'is-1-mobile',
  TwoMobile = 'is-2-mobile',
  ThreeMobile = 'is-3-mobile',
  FourMobile = 'is-4-mobile',
  FiveMobile = 'is-5-mobile',
  SixMobile = 'is-6-mobile',
  SevenMobile = 'is-7-mobile',
  EightMobile = 'is-8-mobile',
  NineMobile = 'is-9-mobile',
  TenMobile = 'is-10-mobile',
  ElevenMobile = 'is-11-mobile',
  TwelveMobile = 'is-12-mobile',

  OneTablet = 'is-1-tablet',
  TwoTablet = 'is-2-tablet',
  ThreeTablet = 'is-3-tablet',
  FourTablet = 'is-4-tablet',
  FiveTablet = 'is-5-tablet',
  SixTablet = 'is-6-tablet',
  SevenTablet = 'is-7-tablet',
  EightTablet = 'is-8-tablet',
  NineTablet = 'is-9-tablet',
  TenTablet = 'is-10-tablet',
  ElevenTablet = 'is-11-tablet',
  TwelveTablet = 'is-12-tablet',

  OneDesktop = 'is-1-desktop',
  TwoDesktop = 'is-2-desktop',
  ThreeDesktop = 'is-3-desktop',
  FourDesktop = 'is-4-desktop',
  FiveDesktop = 'is-5-desktop',
  SixDesktop = 'is-6-desktop',
  SevenDesktop = 'is-7-desktop',
  EightDesktop = 'is-8-desktop',
  NineDesktop = 'is-9-desktop',
  TenDesktop = 'is-10-desktop',
  ElevenDesktop = 'is-11-desktop',
  TwelveDesktop = 'is-12-desktop',

  OneWidescreen = 'is-1-widescreen',
  TwoWidescreen = 'is-2-widescreen',
  ThreeWidescreen = 'is-3-widescreen',
  FourWidescreen = 'is-4-widescreen',
  FiveWidescreen = 'is-5-widescreen',
  SixWidescreen = 'is-6-widescreen',
  SevenWidescreen = 'is-7-widescreen',
  EightWidescreen = 'is-8-widescreen',
  NineWidescreen = 'is-9-widescreen',
  TenWidescreen = 'is-10-widescreen',
  ElevenWidescreen = 'is-11-widescreen',
  TwelveWidescreen = 'is-12-widescreen',

  OneFullHD = 'is-1-fullhd',
  TwoFullHD = 'is-2-fullhd',
  ThreeFullHD = 'is-3-fullhd',
  FourFullHD = 'is-4-fullhd',
  FiveFullHD = 'is-5-fullhd',
  SixFullHD = 'is-6-fullhd',
  SevenFullHD = 'is-7-fullhd',
  EightFullHD = 'is-8-fullhd',
  NineFullHD = 'is-9-fullhd',
  TenFullHD = 'is-10-fullhd',
  ElevenFullHD = 'is-11-fullhd',
  TwelveFullHD = 'is-12-fullhd',
}