export enum ColumnOffset {
  ThreeQuarters = 'is-offset-three-quarters',
  TwoThirds = 'is-offset-two-thirds',
  Half = 'is-offset-half',
  OneThird = 'is-offset-one-third',
  OneQuarter = 'is-offset-one-quarter',
  Full = 'is-offset-full',
  FourFifths = 'is-offset-four-fifths',
  ThreeFifths = 'is-offset-three-fifths',
  TwoFifths = 'is-offset-two-fifths',
  OneFifths = 'is-offset-one-fifth',

  // 12 columns system
  One = 'is-offset-1',
  Two = 'is-offset-2',
  Three = 'is-offset-3',
  Four = 'is-offset-4',
  Five = 'is-offset-5',
  Six = 'is-offset-6',
  Seven = 'is-offset-7',
  Eight = 'is-offset-8',
  Nine = 'is-offset-9',
  Ten = 'is-offset-10',
  Eleven = 'is-offset-11',
  Twelve = 'is-offset-12',
}