export enum ColumnGap {
  Default = '',
  GapLess = 'is-gapless',

  // Variable
  Zero = 'is-variable is-0',
  One = 'is-variable is-1',
  Two = 'is-variable is-2',
  Three = 'is-variable is-3',
  Four = 'is-variable is-4',
  Five = 'is-variable is-5',
  Six = 'is-variable is-6',
  Seven = 'is-variable is-7',
  Eight = 'is-variable is-8',

  ZeroMobile = 'is-variable is-0-mobile',
  OneMobile = 'is-variable is-1-mobile',
  TwoMobile = 'is-variable is-2-mobile',
  ThreeMobile = 'is-variable is-3-mobile',
  FourMobile = 'is-variable is-4-mobile',
  FiveMobile = 'is-variable is-5-mobile',
  SixMobile = 'is-variable is-6-mobile',
  SevenMobile = 'is-variable is-7-mobile',
  EightMobile = 'is-variable is-8-mobile',

  ZeroTablet = 'is-variable is-0-tablet',
  OneTablet = 'is-variable is-1-tablet',
  TwoTablet = 'is-variable is-2-tablet',
  ThreeTablet = 'is-variable is-3-tablet',
  FourTablet = 'is-variable is-4-tablet',
  FiveTablet = 'is-variable is-5-tablet',
  SixTablet = 'is-variable is-6-tablet',
  SevenTablet = 'is-variable is-7-tablet',
  EightTablet = 'is-variable is-8-tablet',

  ZeroDesktop = 'is-variable is-0-desktop',
  OneDesktop = 'is-variable is-1-desktop',
  TwoDesktop = 'is-variable is-2-desktop',
  ThreeDesktop = 'is-variable is-3-desktop',
  FourDesktop = 'is-variable is-4-desktop',
  FiveDesktop = 'is-variable is-5-desktop',
  SixDesktop = 'is-variable is-6-desktop',
  SevenDesktop = 'is-variable is-7-desktop',
  EightDesktop = 'is-variable is-8-desktop',

  ZeroWidescreen = 'is-variable is-0-widescreen',
  OneWidescreen = 'is-variable is-1-widescreen',
  TwoWidescreen = 'is-variable is-2-widescreen',
  ThreeWidescreen = 'is-variable is-3-widescreen',
  FourWidescreen = 'is-variable is-4-widescreen',
  FiveWidescreen = 'is-variable is-5-widescreen',
  SixWidescreen = 'is-variable is-6-widescreen',
  SevenWidescreen = 'is-variable is-7-widescreen',
  EightWidescreen = 'is-variable is-8-widescreen',

  ZeroFullHD = 'is-variable is-0-fullhd',
  OneFullHD = 'is-variable is-1-fullhd',
  TwoFullHD = 'is-variable is-2-fullhd',
  ThreeFullHD = 'is-variable is-3-fullhd',
  FourFullHD = 'is-variable is-4-fullhd',
  FiveFullHD = 'is-variable is-5-fullhd',
  SixFullHD = 'is-variable is-6-fullhd',
  SevenFullHD = 'is-variable is-7-fullhd',
  EightFullHD = 'is-variable is-8-fullhd',
}