"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const React = require("react");
const react_dom_1 = require("react-dom");
const main_1 = require("./main");
if (require.main !== module) {
    react_dom_1.render(React.createElement("div", null,
        React.createElement(main_1.default.Hero, { color: main_1.default.Colors.Link },
            React.createElement(main_1.default.HeroBody, null,
                React.createElement(main_1.default.Container, null,
                    React.createElement(main_1.default.Columns, null,
                        React.createElement(main_1.default.Column, null,
                            React.createElement(main_1.default.Title, null, "Documentation"),
                            React.createElement(main_1.default.Subtitle, null,
                                "Everything you need to ",
                                React.createElement("strong", null, "create a website"),
                                " with Bulma")),
                        React.createElement(main_1.default.Column, { narrow: main_1.default.Narrow.All },
                            React.createElement(main_1.default.Box, null, "ADS"))))),
            React.createElement(main_1.default.HeroFoot, null,
                React.createElement(main_1.default.Container, null,
                    React.createElement(main_1.default.Tabs, { styles: main_1.default.TabsStyles.Boxed },
                        React.createElement(main_1.default.Tab, { active: true }, "Overview"),
                        React.createElement(main_1.default.Tab, null, "Modifiers"),
                        React.createElement(main_1.default.Tab, null, "Columns"),
                        React.createElement(main_1.default.Tab, null, "Layout"),
                        React.createElement(main_1.default.Tab, null, "Form"),
                        React.createElement(main_1.default.Tab, null, "Elements"),
                        React.createElement(main_1.default.Tab, null, "Components"))))),
        React.createElement(main_1.default.Navbar, { hasShadow: true },
            React.createElement(main_1.default.Container, null,
                React.createElement(main_1.default.NavbarTabs, null,
                    React.createElement(main_1.default.NavbarItem, { tab: true, active: true }, "Start"),
                    React.createElement(main_1.default.NavbarItem, { tab: true }, "Customize"),
                    React.createElement(main_1.default.NavbarItem, { tab: true }, "Classes"),
                    React.createElement(main_1.default.NavbarItem, { tab: true }, "Modular"),
                    React.createElement(main_1.default.NavbarItem, { tab: true }, "Responsiveness"),
                    React.createElement(main_1.default.NavbarItem, { tab: true }, "Variables"),
                    React.createElement(main_1.default.NavbarItem, { tab: true }, "Colors"),
                    React.createElement(main_1.default.NavbarItem, { tab: true }, "Functions"),
                    React.createElement(main_1.default.NavbarItem, { tab: true }, "Mixins")))),
        React.createElement(main_1.default.Section, null,
            React.createElement(main_1.default.Container, null,
                React.createElement(main_1.default.Title, null, "Getting started"),
                React.createElement(main_1.default.Subtitle, null,
                    "You only need ",
                    React.createElement("strong", null, "1 CSS file"),
                    " to use Bulma"),
                React.createElement("hr", null),
                React.createElement(main_1.default.Content, null,
                    React.createElement("p", null,
                        "There are several ways to ",
                        React.createElement("strong", null, "get started"),
                        " with Bulma. You can either:"),
                    React.createElement("ol", null,
                        React.createElement("li", null,
                            "use ",
                            React.createElement("strong", null, "npm"),
                            " to install the Bulma package"),
                        React.createElement("li", null,
                            "use the cdnjs ",
                            React.createElement("strong", null, "CDN"),
                            " to link to the Bulma stylesheet"),
                        React.createElement("li", null,
                            "use the ",
                            React.createElement("strong", null, "GitHub repository"),
                            " to get the latest development version"))),
                React.createElement(main_1.default.Media, null,
                    React.createElement(main_1.default.MediaLeft, null,
                        React.createElement(main_1.default.Title, { size: main_1.default.TitleSizes.Five }, "1")),
                    React.createElement(main_1.default.MediaContent, null,
                        React.createElement(main_1.default.Title, { size: main_1.default.TitleSizes.Five },
                            "Use ",
                            React.createElement("strong", null, "NPM"),
                            " ",
                            React.createElement("em", null, "(recommended)"),
                            ":"),
                        React.createElement("figure", null,
                            React.createElement("pre", null,
                                React.createElement("code", null, "npm install bulma"))))),
                React.createElement(main_1.default.Media, null,
                    React.createElement(main_1.default.MediaLeft, null,
                        React.createElement(main_1.default.Title, { size: main_1.default.TitleSizes.Five }, "2")),
                    React.createElement(main_1.default.MediaContent, null,
                        React.createElement(main_1.default.Title, { size: main_1.default.TitleSizes.Five },
                            "Use the ",
                            React.createElement("a", { href: "https://cdnjs.com/", target: "_blank" }, "cdnjs"),
                            " ",
                            React.createElement("strong", null, "CDN"),
                            React.createElement("br", null),
                            React.createElement("a", { href: "https://cdnjs.com/libraries/bulma" }, "https://cdnjs.com/libraries/bulma")))),
                React.createElement(main_1.default.Media, null,
                    React.createElement(main_1.default.MediaLeft, null,
                        React.createElement(main_1.default.Title, { size: main_1.default.TitleSizes.Five }, "3")),
                    React.createElement(main_1.default.MediaContent, null,
                        React.createElement(main_1.default.Title, { size: main_1.default.TitleSizes.Five },
                            "Download from the ",
                            React.createElement("strong", null, "repository"),
                            React.createElement("br", null),
                            React.createElement("a", { href: "https://github.com/jgthms/bulma/tree/master/css" }, "https://github.com/jgthms/bulma/tree/master/css")))),
                React.createElement("hr", null),
                React.createElement(main_1.default.Message, { color: main_1.default.Colors.Info },
                    React.createElement(main_1.default.MessageHeader, null, "Font Awesome icons"),
                    React.createElement(main_1.default.MessageBody, null,
                        React.createElement("p", null,
                            "If you want to use icons with Bulma, don't forget to include ",
                            React.createElement("a", { href: "https://fortawesome.github.io/Font-Awesome/" }, "Font Awesome"),
                            ":"),
                        React.createElement("figure", null,
                            React.createElement("pre", null,
                                React.createElement("code", null, "<link rel=\"stylesheet\"href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">"))))),
                React.createElement("hr", null),
                React.createElement(main_1.default.Title, { size: main_1.default.TitleSizes.Four }, "Starter template"),
                React.createElement(main_1.default.Content, null,
                    React.createElement("p", null,
                        "If you want to get started ",
                        React.createElement("strong", null, "right away"),
                        ", you can use this ",
                        React.createElement("strong", null, "HTML starter template"),
                        ". Just copy/paste this code in a file and save it on your computer.")),
                React.createElement("div", null,
                    React.createElement("figure", null,
                        React.createElement("pre", null,
                            React.createElement("code", null, "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> <title>Hello Bulma!</title> <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\"> <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.0/css/bulma.min.css\"> </head> <body> <section class=\"section\"> <div class=\"container\"> <h1 class=\"title\"> Hello World </h1> <p class=\"subtitle\"> My first website with <strong>Bulma</strong>! </p> </div> </section> </body> </html>"))))))), document.getElementById('root'));
}
//# sourceMappingURL=index.js.map