"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const React = require("react");
const react_dom_1 = require("react-dom");
const bulma = require("./main");
if (require.main !== module) {
    react_dom_1.render(React.createElement("div", null,
        React.createElement(bulma.Container, null,
            React.createElement(bulma.Navbar, null,
                React.createElement(bulma.NavbarBrand, null,
                    React.createElement(bulma.NavbarItem, { href: "https://bulma.io" },
                        React.createElement("img", { src: "https://bulma.io/images/bulma-logo.png", alt: "Bulma: a modern CSS framework based on Flexbox", height: "28", width: "112" }))),
                React.createElement(bulma.NavbarMenu, null,
                    React.createElement(bulma.NavbarStart, null,
                        React.createElement(bulma.NavbarItem, { hasDropdown: true, hoverable: true },
                            React.createElement(bulma.NavbarLink, { href: "/documentation/overview/start/" }, "Docs"),
                            React.createElement(bulma.NavbarDropdown, null,
                                React.createElement(bulma.NavbarItem, { href: "/documentation/overview/start/" }, "Overview"),
                                React.createElement(bulma.NavbarItem, { href: "https://bulma.io/documentation/modifiers/syntax/" }, "Modifiers"),
                                React.createElement(bulma.NavbarItem, { href: "https://bulma.io/documentation/columns/basics/" }, "Columns"),
                                React.createElement(bulma.NavbarItem, { href: "https://bulma.io/documentation/layout/container/" }, "Layout"),
                                React.createElement(bulma.NavbarItem, { href: "https://bulma.io/documentation/form/general/" }, "Form"),
                                React.createElement(bulma.NavbarItem, { href: "https://bulma.io/documentation/elements/box/" }, "Elements"),
                                React.createElement(bulma.NavbarItem, { href: "https://bulma.io/documentation/components/breadcrumb/" }, "Components"),
                                React.createElement(bulma.NavbarItem, { href: "https://bulma.io/documentation/modifiers/syntax/" }, "Elements"),
                                React.createElement(bulma.NavbarDivider, null),
                                React.createElement(bulma.NavbarItem, null,
                                    React.createElement("div", null,
                                        React.createElement("p", { className: bulma.ResponsiveSize.size6Desktop },
                                            React.createElement("strong", null, "Version 0.6.0")),
                                        React.createElement("small", null,
                                            React.createElement("a", { href: "https://versions.bulma.io/" }, "View all versions"))))))),
                    React.createElement(bulma.NavbarEnd, null)))),
        React.createElement(bulma.Hero, { color: bulma.Colors.Link },
            React.createElement(bulma.HeroBody, null,
                React.createElement(bulma.Container, null,
                    React.createElement(bulma.Columns, null,
                        React.createElement(bulma.Column, null,
                            React.createElement(bulma.Title, null, "Documentation"),
                            React.createElement(bulma.Subtitle, null,
                                "Everything you need to ",
                                React.createElement("strong", null, "create a website"),
                                " with Bulma")),
                        React.createElement(bulma.Column, { narrow: bulma.Narrow.All },
                            React.createElement(bulma.Box, null, "ADS"))))),
            React.createElement(bulma.HeroFoot, null,
                React.createElement(bulma.Container, null,
                    React.createElement(bulma.Tabs, { styles: bulma.TabsStyles.Boxed },
                        React.createElement(bulma.Tab, { active: true }, "Overview"),
                        React.createElement(bulma.Tab, null, "Modifiers"),
                        React.createElement(bulma.Tab, null, "Columns"),
                        React.createElement(bulma.Tab, null, "Layout"),
                        React.createElement(bulma.Tab, null, "Form"),
                        React.createElement(bulma.Tab, null, "Elements"),
                        React.createElement(bulma.Tab, null, "Components"))))),
        React.createElement(bulma.Navbar, { hasShadow: true },
            React.createElement(bulma.Container, null,
                React.createElement(bulma.NavbarTabs, null,
                    React.createElement(bulma.NavbarItem, { tab: true, active: true }, "Start"),
                    React.createElement(bulma.NavbarItem, { tab: true }, "Customize"),
                    React.createElement(bulma.NavbarItem, { tab: true }, "Classes"),
                    React.createElement(bulma.NavbarItem, { tab: true }, "Modular"),
                    React.createElement(bulma.NavbarItem, { tab: true }, "Responsiveness"),
                    React.createElement(bulma.NavbarItem, { tab: true }, "Variables"),
                    React.createElement(bulma.NavbarItem, { tab: true }, "Colors"),
                    React.createElement(bulma.NavbarItem, { tab: true }, "Functions"),
                    React.createElement(bulma.NavbarItem, { tab: true }, "Mixins")))),
        React.createElement(bulma.Section, null,
            React.createElement(bulma.Container, null,
                React.createElement(bulma.Title, null, "Getting started"),
                React.createElement(bulma.Subtitle, null,
                    "You only need ",
                    React.createElement("strong", null, "1 CSS file"),
                    " to use Bulma"),
                React.createElement("hr", null),
                React.createElement(bulma.Content, null,
                    React.createElement("p", null,
                        "There are several ways to ",
                        React.createElement("strong", null, "get started"),
                        " with Bulma. You can either:"),
                    React.createElement("ol", null,
                        React.createElement("li", null,
                            "use ",
                            React.createElement("strong", null, "npm"),
                            " to install the Bulma package"),
                        React.createElement("li", null,
                            "use the cdnjs ",
                            React.createElement("strong", null, "CDN"),
                            " to link to the Bulma stylesheet"),
                        React.createElement("li", null,
                            "use the ",
                            React.createElement("strong", null, "GitHub repository"),
                            " to get the latest development version"))),
                React.createElement(bulma.Media, null,
                    React.createElement(bulma.MediaLeft, null,
                        React.createElement(bulma.Title, { size: bulma.TitleSizes.Five }, "1")),
                    React.createElement(bulma.MediaContent, null,
                        React.createElement(bulma.Title, { size: bulma.TitleSizes.Five },
                            "Use ",
                            React.createElement("strong", null, "NPM"),
                            " ",
                            React.createElement("em", null, "(recommended)"),
                            ":"),
                        React.createElement("figure", null,
                            React.createElement("pre", null,
                                React.createElement("code", null, `npm install bulma`))))),
                React.createElement(bulma.Media, null,
                    React.createElement(bulma.MediaLeft, null,
                        React.createElement(bulma.Title, { size: bulma.TitleSizes.Five }, "2")),
                    React.createElement(bulma.MediaContent, null,
                        React.createElement(bulma.Title, { size: bulma.TitleSizes.Five },
                            "Use the ",
                            React.createElement("a", { href: "https://cdnjs.com/", target: "_blank" }, "cdnjs"),
                            " ",
                            React.createElement("strong", null, "CDN"),
                            React.createElement("br", null),
                            React.createElement("a", { href: "https://cdnjs.com/libraries/bulma" }, "https://cdnjs.com/libraries/bulma")))),
                React.createElement(bulma.Media, null,
                    React.createElement(bulma.MediaLeft, null,
                        React.createElement(bulma.Title, { size: bulma.TitleSizes.Five }, "3")),
                    React.createElement(bulma.MediaContent, null,
                        React.createElement(bulma.Title, { size: bulma.TitleSizes.Five },
                            "Download from the ",
                            React.createElement("strong", null, "repository"),
                            React.createElement("br", null),
                            React.createElement("a", { href: "https://github.com/jgthms/bulma/tree/master/css" }, "https://github.com/jgthms/bulma/tree/master/css")))),
                React.createElement("hr", null),
                React.createElement(bulma.Message, { color: bulma.Colors.Info },
                    React.createElement(bulma.MessageHeader, null, "Font Awesome icons"),
                    React.createElement(bulma.MessageBody, null,
                        React.createElement("p", null,
                            "If you want to use icons with Bulma, don't forget to include ",
                            React.createElement("a", { href: "https://fortawesome.github.io/Font-Awesome/" }, "Font Awesome"),
                            ":"),
                        React.createElement("figure", null,
                            React.createElement("pre", null,
                                React.createElement("code", null, `<link rel="stylesheet"href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">`))))),
                React.createElement("hr", null),
                React.createElement(bulma.Title, { size: bulma.TitleSizes.Four }, "Starter template"),
                React.createElement(bulma.Content, null,
                    React.createElement("p", null,
                        "If you want to get started ",
                        React.createElement("strong", null, "right away"),
                        ", you can use this ",
                        React.createElement("strong", null, "HTML starter template"),
                        ". Just copy/paste this code in a file and save it on your computer.")),
                React.createElement("figure", null,
                    React.createElement("pre", null,
                        React.createElement("code", null, `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.0/css/bulma.min.css">
</head>
<body>
<section class="section">
  <div class="container">
    <h1 class="title">
      Hello World
    </h1>
    <p class="subtitle">
      My first website with <strong>Bulma</strong>!
    </p>
  </div>
</section>
</body>
</html>`))))),
        React.createElement(bulma.Section, null,
            React.createElement(bulma.Container, null,
                React.createElement("p", { className: bulma.TextAlignment.Cenered + ' ' + bulma.TextColors.GrayLight },
                    React.createElement("img", { src: "https://bulma.io/images/made-with-bulma.png", alt: "Made with Bulma", height: "24", width: "128" }),
                    React.createElement("br", null),
                    "This page is ",
                    React.createElement("strong", { className: bulma.TextColors.Gray }, "open source"),
                    ". Noticed a typo? Or something unclear?",
                    React.createElement("a", { className: bulma.TextColors.Gray, href: "https://github.com/jgthms/bulma/blob/master/docs/documentation/overview/start.html", style: { 'border-bottom': '1px solid currentColor' } }, "Improve this page on GitHub")))),
        React.createElement(bulma.Hero, { color: bulma.Colors.Info },
            React.createElement(bulma.Container, null,
                React.createElement(bulma.Columns, null,
                    React.createElement(bulma.Column, { size: bulma.TwelveColumnsSystem.Four },
                        React.createElement(bulma.Title, null,
                            "Bulma ",
                            React.createElement("strong", null, "Partners")),
                        React.createElement(bulma.Subtitle, null, "Check out their products!")),
                    React.createElement(bulma.Column, { size: bulma.TwelveColumnsSystem.Eight }, "ADS"))))), document.getElementById('root'));
}
//# sourceMappingURL=index.js.map